In [ ]:
import pandas as pd
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a.reshape(-1, 1)


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
a.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [ ]:
a.shape

(2, 5)

In [ ]:
print(a.reshape(5,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
a.size

10

In [ ]:
rating = pd.read_csv("/content/drive/MyDrive/BrainyBeam/cloths-rating.csv")
rating.head()

ProductID  ...                                               Text
0        777  ...                      Great taffy at a great price.
1        767  ...  Absolutely wonderful - silky and sexy and comf...
2       1080  ...                 Love this dress! it's sooo pretty.
3       1077  ...  I had such high hopes for this dress and reall...
4       1049  ...  I love, love, love this jumpsuit. it's fun, fl...

[5 rows x 4 columns]

In [ ]:
rating.columns

Index(['ProductID', 'UserID', 'Rating', 'Text'], dtype='object')

In [ ]:
rating[["UserID", "Rating"]].head()

UserID  Rating
0  AV1YnR7wglJLPUi8IJmi       4
1  AVpfpK8KLJeJML43BCuD       4
2  AVqkIdntQMlgsOJE6fuB       5
3  AVpfpK8KLJeJML43BCuD       3
4  AVpfpK8KLJeJML43BCuD       5

In [ ]:
five = rating[rating.Rating == 5][["UserID", "Rating"]]
five
rating["Rating"]*=2
rating

ProductID  ...                                               Text
0          777  ...                      Great taffy at a great price.
1          767  ...  Absolutely wonderful - silky and sexy and comf...
2         1080  ...                 Love this dress! it's sooo pretty.
3         1077  ...  I had such high hopes for this dress and reall...
4         1049  ...  I love, love, love this jumpsuit. it's fun, fl...
..         ...  ...                                                ...
629        823  ...  I placed order 4+1 soaps.But I have received w...
630        823  ...  The soap is ok for bathing, no scent at all, m...
631        847  ...  For a long time I was searching for Indian soa...
632        910  ...                                 Good but not great
633        333  ...                    Quick,easy to make & tasty too.

[634 rows x 4 columns]

In [ ]:
a = [1, 2, 3, 4, 5, 6]
b = [5, 6, 8, 0, 8, 9]
a1 = pd.Series(a)
b1 = pd.Series(b)
df = pd.DataFrame(a, b)
df = pd.DataFrame(a, b, columns = ["A"])
df = a1+b1
df

0     6
1     8
2    11
3     4
4    13
5    15
dtype: int64

In [ ]:
rating.groupby(["Rating"])["UserID"].count()

Rating
0       1
2     125
4      34
6      48
8      86
10    340
Name: UserID, dtype: int64

In [ ]:
a = {"a": [1, 2, 3, 4], "b": [4, 6, 7, 8], "c": [3, 6, 8, 9]}
df = pd.DataFrame(a)
df

a  b  c
0  1  4  3
1  2  6  6
2  3  7  8
3  4  8  9

In [ ]:
a = np.array([1, 2, 2, 4, 5, 6])
b = np.array([1, 2, 3, 4, 5, 6])
a1 = pd.Series(a)
b1 = pd.Series(b)
df = pd.concat([a1, b1], axis = 1)
df

0  1
0  1  1
1  2  2
2  2  3
3  4  4
4  5  5
5  6  6

In [ ]:
q = pd.Series([1, 2, 3, 4])
w = pd.Series([5, 6, 7, 8])
d = {"a": q, "b": w}
df = pd.DataFrame(d)
df

a  b
0  1  5
1  2  6
2  3  7
3  4  8

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([10, 20, 30, 40, 50])
testing = np.array([7, 8])
model = LinearRegression()
model.fit(x.reshape(-1, 1), y)
model.predict(testing.reshape(-1, 1))

array([70., 80.])

In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([14, 26, 37, 48, 59])
testing = np.array([6, 7, 8])
model = LinearRegression()
model.fit(x.reshape(-1, 1), y)
model.predict(testing.reshape(-1, 1))

array([70.4, 81.6, 92.8])

In [ ]:
model.coef_

array([11.2])

In [ ]:
model.intercept_

3.1999999999999957